// import_nieuwe_testen.js
// Voegt 4 nieuwe testen toe (testen-collectie) + bijhorende normen (normen-collectie).
// Testen: verspringen uit stand (kracht), sit-up 30s (uithouding),
//         sit & reach (lenigheid), max triceps dips (kracht).
// Normen: mix realistisch (p10 ~ mediaan) / ambitieus (p20 ~ 95e pct), 14-17j, M+V.
// Sit & reach: VERSCHOVEN schaal (+15) zodat tenen raken = 15, geen negatieve waarden.
// MARKER_NIEUWE_TESTEN_2026_09
import admin from 'firebase-admin';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const serviceAccount = require('./serviceAccountKey.json');

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
  });
}

const db = admin.firestore();
const TS = admin.firestore.FieldValue.serverTimestamp();

// ─────────────────────────── TESTEN ───────────────────────────
const testen = {
  'verspringen_stand': {
    naam: "Verspringen uit stand",
    beschrijving: "Doel: spring vanuit stilstand zo ver mogelijk voorwaarts met beide voeten. Procedure: 1. Sta met beide voeten achter de afzetstreep. 2. Zwaai met de armen en zet krachtig af met beide voeten tegelijk. 3. Land op beide voeten. 4. Gemeten wordt de afstand van de afzetstreep tot de achterste hiel. Beste van 3 pogingen telt. Meet explosieve beenkracht.",
    categorie: "Kracht",
    eenheid: "cm",
    score_richting: "hoog",
    max_punten: 20,
    is_actief: true,
    school_id: "ka_beveren",
    created_at: TS,
    last_updated_at: TS
  },
  'sit_up_30s': {
    naam: "Sit-up (30 sec)",
    beschrijving: "Doel: voer zoveel mogelijk correcte sit-ups uit in 30 seconden. Procedure: 1. Lig op de rug, knieën 90°, handen in de nek, voeten door partner vastgehouden. 2. Kom op tot de ellebogen de knieën raken, ga terug tot de rug de mat raakt. 3. Tel het aantal correcte herhalingen in 30 seconden. Meet romp-uithouding.",
    categorie: "Uithouding",
    eenheid: "aantal",
    score_richting: "hoog",
    max_punten: 20,
    is_actief: true,
    school_id: "ka_beveren",
    created_at: TS,
    last_updated_at: TS
  },
  'sit_and_reach': {
    naam: "Zit en reik (sit & reach)",
    beschrijving: "Doel: reik vanuit zit zo ver mogelijk voorwaarts. Procedure: 1. Zit met gestrekte benen, voetzolen plat tegen de meetbox. 2. Reik langzaam zo ver mogelijk voorwaarts langs de schaal, houd de positie 2 sec vast. Meet lenigheid van hamstrings en onderrug. LET OP: verschoven schaal — tenen raken = 15 cm, verder reiken = hoger, minder ver = lager (nooit negatief).",
    categorie: "Lenigheid",
    eenheid: "cm",
    score_richting: "hoog",
    max_punten: 20,
    is_actief: true,
    school_id: "ka_beveren",
    created_at: TS,
    last_updated_at: TS
  },
  'triceps_dips': {
    naam: "Triceps dips (max)",
    beschrijving: "Doel: voer zoveel mogelijk correcte dips uit tot uitputting (geen tijdslimiet). Procedure: 1. Steun met de handen op een bank/barre, benen gestrekt of geknikt. 2. Zak tot de ellebogen ~90° buigen, duw terug tot volledige strekking. 3. Tel het aantal correcte herhalingen tot je niet meer kan. Meet triceps- en schouderkracht.",
    categorie: "Kracht",
    eenheid: "aantal",
    score_richting: "hoog",
    max_punten: 20,
    is_actief: true,
    school_id: "ka_beveren",
    created_at: TS,
    last_updated_at: TS
  }
};

// ─────────────────────────── NORMEN ───────────────────────────
const normen = {
  'normen_verspringen_stand': {
    "test_id": "verspringen_stand",
    "school_id": "ka_beveren",
    "score_richting": "hoog",
    "punten_schaal": [
      // Jongens
      // 14 jaar
      { geslacht: "M", leeftijd: 14, punt: 1, score_min: 120 },
      { geslacht: "M", leeftijd: 14, punt: 2, score_min: 127 },
      { geslacht: "M", leeftijd: 14, punt: 3, score_min: 135 },
      { geslacht: "M", leeftijd: 14, punt: 4, score_min: 142 },
      { geslacht: "M", leeftijd: 14, punt: 5, score_min: 150 },
      { geslacht: "M", leeftijd: 14, punt: 6, score_min: 157 },
      { geslacht: "M", leeftijd: 14, punt: 7, score_min: 165 },
      { geslacht: "M", leeftijd: 14, punt: 8, score_min: 172 },
      { geslacht: "M", leeftijd: 14, punt: 9, score_min: 180 },
      { geslacht: "M", leeftijd: 14, punt: 10, score_min: 187 },
      { geslacht: "M", leeftijd: 14, punt: 11, score_min: 191 },
      { geslacht: "M", leeftijd: 14, punt: 12, score_min: 195 },
      { geslacht: "M", leeftijd: 14, punt: 13, score_min: 198 },
      { geslacht: "M", leeftijd: 14, punt: 14, score_min: 202 },
      { geslacht: "M", leeftijd: 14, punt: 15, score_min: 206 },
      { geslacht: "M", leeftijd: 14, punt: 16, score_min: 210 },
      { geslacht: "M", leeftijd: 14, punt: 17, score_min: 214 },
      { geslacht: "M", leeftijd: 14, punt: 18, score_min: 217 },
      { geslacht: "M", leeftijd: 14, punt: 19, score_min: 221 },
      { geslacht: "M", leeftijd: 14, punt: 20, score_min: 225 },
      // 15 jaar
      { geslacht: "M", leeftijd: 15, punt: 1, score_min: 130 },
      { geslacht: "M", leeftijd: 15, punt: 2, score_min: 137 },
      { geslacht: "M", leeftijd: 15, punt: 3, score_min: 144 },
      { geslacht: "M", leeftijd: 15, punt: 4, score_min: 152 },
      { geslacht: "M", leeftijd: 15, punt: 5, score_min: 159 },
      { geslacht: "M", leeftijd: 15, punt: 6, score_min: 166 },
      { geslacht: "M", leeftijd: 15, punt: 7, score_min: 173 },
      { geslacht: "M", leeftijd: 15, punt: 8, score_min: 181 },
      { geslacht: "M", leeftijd: 15, punt: 9, score_min: 188 },
      { geslacht: "M", leeftijd: 15, punt: 10, score_min: 195 },
      { geslacht: "M", leeftijd: 15, punt: 11, score_min: 199 },
      { geslacht: "M", leeftijd: 15, punt: 12, score_min: 203 },
      { geslacht: "M", leeftijd: 15, punt: 13, score_min: 207 },
      { geslacht: "M", leeftijd: 15, punt: 14, score_min: 211 },
      { geslacht: "M", leeftijd: 15, punt: 15, score_min: 215 },
      { geslacht: "M", leeftijd: 15, punt: 16, score_min: 219 },
      { geslacht: "M", leeftijd: 15, punt: 17, score_min: 223 },
      { geslacht: "M", leeftijd: 15, punt: 18, score_min: 227 },
      { geslacht: "M", leeftijd: 15, punt: 19, score_min: 231 },
      { geslacht: "M", leeftijd: 15, punt: 20, score_min: 235 },
      // 16 jaar
      { geslacht: "M", leeftijd: 16, punt: 1, score_min: 140 },
      { geslacht: "M", leeftijd: 16, punt: 2, score_min: 147 },
      { geslacht: "M", leeftijd: 16, punt: 3, score_min: 154 },
      { geslacht: "M", leeftijd: 16, punt: 4, score_min: 162 },
      { geslacht: "M", leeftijd: 16, punt: 5, score_min: 169 },
      { geslacht: "M", leeftijd: 16, punt: 6, score_min: 176 },
      { geslacht: "M", leeftijd: 16, punt: 7, score_min: 183 },
      { geslacht: "M", leeftijd: 16, punt: 8, score_min: 191 },
      { geslacht: "M", leeftijd: 16, punt: 9, score_min: 198 },
      { geslacht: "M", leeftijd: 16, punt: 10, score_min: 205 },
      { geslacht: "M", leeftijd: 16, punt: 11, score_min: 209 },
      { geslacht: "M", leeftijd: 16, punt: 12, score_min: 213 },
      { geslacht: "M", leeftijd: 16, punt: 13, score_min: 217 },
      { geslacht: "M", leeftijd: 16, punt: 14, score_min: 221 },
      { geslacht: "M", leeftijd: 16, punt: 15, score_min: 225 },
      { geslacht: "M", leeftijd: 16, punt: 16, score_min: 229 },
      { geslacht: "M", leeftijd: 16, punt: 17, score_min: 233 },
      { geslacht: "M", leeftijd: 16, punt: 18, score_min: 237 },
      { geslacht: "M", leeftijd: 16, punt: 19, score_min: 241 },
      { geslacht: "M", leeftijd: 16, punt: 20, score_min: 245 },
      // 17 jaar
      { geslacht: "M", leeftijd: 17, punt: 1, score_min: 145 },
      { geslacht: "M", leeftijd: 17, punt: 2, score_min: 152 },
      { geslacht: "M", leeftijd: 17, punt: 3, score_min: 159 },
      { geslacht: "M", leeftijd: 17, punt: 4, score_min: 167 },
      { geslacht: "M", leeftijd: 17, punt: 5, score_min: 174 },
      { geslacht: "M", leeftijd: 17, punt: 6, score_min: 181 },
      { geslacht: "M", leeftijd: 17, punt: 7, score_min: 188 },
      { geslacht: "M", leeftijd: 17, punt: 8, score_min: 196 },
      { geslacht: "M", leeftijd: 17, punt: 9, score_min: 203 },
      { geslacht: "M", leeftijd: 17, punt: 10, score_min: 210 },
      { geslacht: "M", leeftijd: 17, punt: 11, score_min: 214 },
      { geslacht: "M", leeftijd: 17, punt: 12, score_min: 218 },
      { geslacht: "M", leeftijd: 17, punt: 13, score_min: 222 },
      { geslacht: "M", leeftijd: 17, punt: 14, score_min: 226 },
      { geslacht: "M", leeftijd: 17, punt: 15, score_min: 230 },
      { geslacht: "M", leeftijd: 17, punt: 16, score_min: 234 },
      { geslacht: "M", leeftijd: 17, punt: 17, score_min: 238 },
      { geslacht: "M", leeftijd: 17, punt: 18, score_min: 242 },
      { geslacht: "M", leeftijd: 17, punt: 19, score_min: 246 },
      { geslacht: "M", leeftijd: 17, punt: 20, score_min: 250 },
      // Meisjes
      // 14 jaar
      { geslacht: "V", leeftijd: 14, punt: 1, score_min: 100 },
      { geslacht: "V", leeftijd: 14, punt: 2, score_min: 106 },
      { geslacht: "V", leeftijd: 14, punt: 3, score_min: 112 },
      { geslacht: "V", leeftijd: 14, punt: 4, score_min: 118 },
      { geslacht: "V", leeftijd: 14, punt: 5, score_min: 124 },
      { geslacht: "V", leeftijd: 14, punt: 6, score_min: 131 },
      { geslacht: "V", leeftijd: 14, punt: 7, score_min: 137 },
      { geslacht: "V", leeftijd: 14, punt: 8, score_min: 143 },
      { geslacht: "V", leeftijd: 14, punt: 9, score_min: 149 },
      { geslacht: "V", leeftijd: 14, punt: 10, score_min: 155 },
      { geslacht: "V", leeftijd: 14, punt: 11, score_min: 159 },
      { geslacht: "V", leeftijd: 14, punt: 12, score_min: 163 },
      { geslacht: "V", leeftijd: 14, punt: 13, score_min: 167 },
      { geslacht: "V", leeftijd: 14, punt: 14, score_min: 171 },
      { geslacht: "V", leeftijd: 14, punt: 15, score_min: 175 },
      { geslacht: "V", leeftijd: 14, punt: 16, score_min: 179 },
      { geslacht: "V", leeftijd: 14, punt: 17, score_min: 183 },
      { geslacht: "V", leeftijd: 14, punt: 18, score_min: 187 },
      { geslacht: "V", leeftijd: 14, punt: 19, score_min: 191 },
      { geslacht: "V", leeftijd: 14, punt: 20, score_min: 195 },
      // 15 jaar
      { geslacht: "V", leeftijd: 15, punt: 1, score_min: 105 },
      { geslacht: "V", leeftijd: 15, punt: 2, score_min: 111 },
      { geslacht: "V", leeftijd: 15, punt: 3, score_min: 117 },
      { geslacht: "V", leeftijd: 15, punt: 4, score_min: 123 },
      { geslacht: "V", leeftijd: 15, punt: 5, score_min: 129 },
      { geslacht: "V", leeftijd: 15, punt: 6, score_min: 134 },
      { geslacht: "V", leeftijd: 15, punt: 7, score_min: 140 },
      { geslacht: "V", leeftijd: 15, punt: 8, score_min: 146 },
      { geslacht: "V", leeftijd: 15, punt: 9, score_min: 152 },
      { geslacht: "V", leeftijd: 15, punt: 10, score_min: 158 },
      { geslacht: "V", leeftijd: 15, punt: 11, score_min: 162 },
      { geslacht: "V", leeftijd: 15, punt: 12, score_min: 166 },
      { geslacht: "V", leeftijd: 15, punt: 13, score_min: 170 },
      { geslacht: "V", leeftijd: 15, punt: 14, score_min: 174 },
      { geslacht: "V", leeftijd: 15, punt: 15, score_min: 178 },
      { geslacht: "V", leeftijd: 15, punt: 16, score_min: 182 },
      { geslacht: "V", leeftijd: 15, punt: 17, score_min: 186 },
      { geslacht: "V", leeftijd: 15, punt: 18, score_min: 190 },
      { geslacht: "V", leeftijd: 15, punt: 19, score_min: 194 },
      { geslacht: "V", leeftijd: 15, punt: 20, score_min: 198 },
      // 16 jaar
      { geslacht: "V", leeftijd: 16, punt: 1, score_min: 108 },
      { geslacht: "V", leeftijd: 16, punt: 2, score_min: 114 },
      { geslacht: "V", leeftijd: 16, punt: 3, score_min: 120 },
      { geslacht: "V", leeftijd: 16, punt: 4, score_min: 125 },
      { geslacht: "V", leeftijd: 16, punt: 5, score_min: 131 },
      { geslacht: "V", leeftijd: 16, punt: 6, score_min: 137 },
      { geslacht: "V", leeftijd: 16, punt: 7, score_min: 143 },
      { geslacht: "V", leeftijd: 16, punt: 8, score_min: 148 },
      { geslacht: "V", leeftijd: 16, punt: 9, score_min: 154 },
      { geslacht: "V", leeftijd: 16, punt: 10, score_min: 160 },
      { geslacht: "V", leeftijd: 16, punt: 11, score_min: 164 },
      { geslacht: "V", leeftijd: 16, punt: 12, score_min: 168 },
      { geslacht: "V", leeftijd: 16, punt: 13, score_min: 172 },
      { geslacht: "V", leeftijd: 16, punt: 14, score_min: 176 },
      { geslacht: "V", leeftijd: 16, punt: 15, score_min: 180 },
      { geslacht: "V", leeftijd: 16, punt: 16, score_min: 184 },
      { geslacht: "V", leeftijd: 16, punt: 17, score_min: 188 },
      { geslacht: "V", leeftijd: 16, punt: 18, score_min: 192 },
      { geslacht: "V", leeftijd: 16, punt: 19, score_min: 196 },
      { geslacht: "V", leeftijd: 16, punt: 20, score_min: 200 },
      // 17 jaar
      { geslacht: "V", leeftijd: 17, punt: 1, score_min: 110 },
      { geslacht: "V", leeftijd: 17, punt: 2, score_min: 116 },
      { geslacht: "V", leeftijd: 17, punt: 3, score_min: 122 },
      { geslacht: "V", leeftijd: 17, punt: 4, score_min: 127 },
      { geslacht: "V", leeftijd: 17, punt: 5, score_min: 133 },
      { geslacht: "V", leeftijd: 17, punt: 6, score_min: 139 },
      { geslacht: "V", leeftijd: 17, punt: 7, score_min: 145 },
      { geslacht: "V", leeftijd: 17, punt: 8, score_min: 150 },
      { geslacht: "V", leeftijd: 17, punt: 9, score_min: 156 },
      { geslacht: "V", leeftijd: 17, punt: 10, score_min: 162 },
      { geslacht: "V", leeftijd: 17, punt: 11, score_min: 166 },
      { geslacht: "V", leeftijd: 17, punt: 12, score_min: 170 },
      { geslacht: "V", leeftijd: 17, punt: 13, score_min: 174 },
      { geslacht: "V", leeftijd: 17, punt: 14, score_min: 178 },
      { geslacht: "V", leeftijd: 17, punt: 15, score_min: 182 },
      { geslacht: "V", leeftijd: 17, punt: 16, score_min: 186 },
      { geslacht: "V", leeftijd: 17, punt: 17, score_min: 190 },
      { geslacht: "V", leeftijd: 17, punt: 18, score_min: 194 },
      { geslacht: "V", leeftijd: 17, punt: 19, score_min: 198 },
      { geslacht: "V", leeftijd: 17, punt: 20, score_min: 202 }
    ]
  },
  'normen_sit_up_30s': {
    "test_id": "sit_up_30s",
    "school_id": "ka_beveren",
    "score_richting": "hoog",
    "punten_schaal": [
      // Jongens
      // 14 jaar
      { geslacht: "M", leeftijd: 14, punt: 1, score_min: 8 },
      { geslacht: "M", leeftijd: 14, punt: 2, score_min: 10 },
      { geslacht: "M", leeftijd: 14, punt: 3, score_min: 11 },
      { geslacht: "M", leeftijd: 14, punt: 4, score_min: 13 },
      { geslacht: "M", leeftijd: 14, punt: 5, score_min: 14 },
      { geslacht: "M", leeftijd: 14, punt: 6, score_min: 16 },
      { geslacht: "M", leeftijd: 14, punt: 7, score_min: 17 },
      { geslacht: "M", leeftijd: 14, punt: 8, score_min: 19 },
      { geslacht: "M", leeftijd: 14, punt: 9, score_min: 20 },
      { geslacht: "M", leeftijd: 14, punt: 10, score_min: 22 },
      { geslacht: "M", leeftijd: 14, punt: 11, score_min: 23 },
      { geslacht: "M", leeftijd: 14, punt: 12, score_min: 24 },
      { geslacht: "M", leeftijd: 14, punt: 13, score_min: 25 },
      { geslacht: "M", leeftijd: 14, punt: 14, score_min: 26 },
      { geslacht: "M", leeftijd: 14, punt: 15, score_min: 27 },
      { geslacht: "M", leeftijd: 14, punt: 16, score_min: 28 },
      { geslacht: "M", leeftijd: 14, punt: 17, score_min: 29 },
      { geslacht: "M", leeftijd: 14, punt: 18, score_min: 30 },
      { geslacht: "M", leeftijd: 14, punt: 19, score_min: 31 },
      { geslacht: "M", leeftijd: 14, punt: 20, score_min: 32 },
      // 15 jaar
      { geslacht: "M", leeftijd: 15, punt: 1, score_min: 9 },
      { geslacht: "M", leeftijd: 15, punt: 2, score_min: 11 },
      { geslacht: "M", leeftijd: 15, punt: 3, score_min: 12 },
      { geslacht: "M", leeftijd: 15, punt: 4, score_min: 14 },
      { geslacht: "M", leeftijd: 15, punt: 5, score_min: 15 },
      { geslacht: "M", leeftijd: 15, punt: 6, score_min: 17 },
      { geslacht: "M", leeftijd: 15, punt: 7, score_min: 18 },
      { geslacht: "M", leeftijd: 15, punt: 8, score_min: 20 },
      { geslacht: "M", leeftijd: 15, punt: 9, score_min: 21 },
      { geslacht: "M", leeftijd: 15, punt: 10, score_min: 23 },
      { geslacht: "M", leeftijd: 15, punt: 11, score_min: 24 },
      { geslacht: "M", leeftijd: 15, punt: 12, score_min: 25 },
      { geslacht: "M", leeftijd: 15, punt: 13, score_min: 26 },
      { geslacht: "M", leeftijd: 15, punt: 14, score_min: 27 },
      { geslacht: "M", leeftijd: 15, punt: 15, score_min: 28 },
      { geslacht: "M", leeftijd: 15, punt: 16, score_min: 29 },
      { geslacht: "M", leeftijd: 15, punt: 17, score_min: 30 },
      { geslacht: "M", leeftijd: 15, punt: 18, score_min: 31 },
      { geslacht: "M", leeftijd: 15, punt: 19, score_min: 32 },
      { geslacht: "M", leeftijd: 15, punt: 20, score_min: 33 },
      // 16 jaar
      { geslacht: "M", leeftijd: 16, punt: 1, score_min: 10 },
      { geslacht: "M", leeftijd: 16, punt: 2, score_min: 12 },
      { geslacht: "M", leeftijd: 16, punt: 3, score_min: 13 },
      { geslacht: "M", leeftijd: 16, punt: 4, score_min: 15 },
      { geslacht: "M", leeftijd: 16, punt: 5, score_min: 16 },
      { geslacht: "M", leeftijd: 16, punt: 6, score_min: 18 },
      { geslacht: "M", leeftijd: 16, punt: 7, score_min: 19 },
      { geslacht: "M", leeftijd: 16, punt: 8, score_min: 21 },
      { geslacht: "M", leeftijd: 16, punt: 9, score_min: 22 },
      { geslacht: "M", leeftijd: 16, punt: 10, score_min: 24 },
      { geslacht: "M", leeftijd: 16, punt: 11, score_min: 25 },
      { geslacht: "M", leeftijd: 16, punt: 12, score_min: 26 },
      { geslacht: "M", leeftijd: 16, punt: 13, score_min: 27 },
      { geslacht: "M", leeftijd: 16, punt: 14, score_min: 28 },
      { geslacht: "M", leeftijd: 16, punt: 15, score_min: 29 },
      { geslacht: "M", leeftijd: 16, punt: 16, score_min: 30 },
      { geslacht: "M", leeftijd: 16, punt: 17, score_min: 31 },
      { geslacht: "M", leeftijd: 16, punt: 18, score_min: 32 },
      { geslacht: "M", leeftijd: 16, punt: 19, score_min: 33 },
      { geslacht: "M", leeftijd: 16, punt: 20, score_min: 34 },
      // 17 jaar
      { geslacht: "M", leeftijd: 17, punt: 1, score_min: 10 },
      { geslacht: "M", leeftijd: 17, punt: 2, score_min: 12 },
      { geslacht: "M", leeftijd: 17, punt: 3, score_min: 13 },
      { geslacht: "M", leeftijd: 17, punt: 4, score_min: 15 },
      { geslacht: "M", leeftijd: 17, punt: 5, score_min: 17 },
      { geslacht: "M", leeftijd: 17, punt: 6, score_min: 18 },
      { geslacht: "M", leeftijd: 17, punt: 7, score_min: 20 },
      { geslacht: "M", leeftijd: 17, punt: 8, score_min: 22 },
      { geslacht: "M", leeftijd: 17, punt: 9, score_min: 23 },
      { geslacht: "M", leeftijd: 17, punt: 10, score_min: 25 },
      { geslacht: "M", leeftijd: 17, punt: 11, score_min: 26 },
      { geslacht: "M", leeftijd: 17, punt: 12, score_min: 27 },
      { geslacht: "M", leeftijd: 17, punt: 13, score_min: 28 },
      { geslacht: "M", leeftijd: 17, punt: 14, score_min: 29 },
      { geslacht: "M", leeftijd: 17, punt: 15, score_min: 30 },
      { geslacht: "M", leeftijd: 17, punt: 16, score_min: 31 },
      { geslacht: "M", leeftijd: 17, punt: 17, score_min: 32 },
      { geslacht: "M", leeftijd: 17, punt: 18, score_min: 33 },
      { geslacht: "M", leeftijd: 17, punt: 19, score_min: 34 },
      { geslacht: "M", leeftijd: 17, punt: 20, score_min: 35 },
      // Meisjes
      // 14 jaar
      { geslacht: "V", leeftijd: 14, punt: 1, score_min: 7 },
      { geslacht: "V", leeftijd: 14, punt: 2, score_min: 8 },
      { geslacht: "V", leeftijd: 14, punt: 3, score_min: 10 },
      { geslacht: "V", leeftijd: 14, punt: 4, score_min: 11 },
      { geslacht: "V", leeftijd: 14, punt: 5, score_min: 12 },
      { geslacht: "V", leeftijd: 14, punt: 6, score_min: 14 },
      { geslacht: "V", leeftijd: 14, punt: 7, score_min: 15 },
      { geslacht: "V", leeftijd: 14, punt: 8, score_min: 16 },
      { geslacht: "V", leeftijd: 14, punt: 9, score_min: 18 },
      { geslacht: "V", leeftijd: 14, punt: 10, score_min: 19 },
      { geslacht: "V", leeftijd: 14, punt: 11, score_min: 20 },
      { geslacht: "V", leeftijd: 14, punt: 12, score_min: 21 },
      { geslacht: "V", leeftijd: 14, punt: 13, score_min: 22 },
      { geslacht: "V", leeftijd: 14, punt: 14, score_min: 23 },
      { geslacht: "V", leeftijd: 14, punt: 15, score_min: 24 },
      { geslacht: "V", leeftijd: 14, punt: 16, score_min: 24 },
      { geslacht: "V", leeftijd: 14, punt: 17, score_min: 25 },
      { geslacht: "V", leeftijd: 14, punt: 18, score_min: 26 },
      { geslacht: "V", leeftijd: 14, punt: 19, score_min: 27 },
      { geslacht: "V", leeftijd: 14, punt: 20, score_min: 28 },
      // 15 jaar
      { geslacht: "V", leeftijd: 15, punt: 1, score_min: 7 },
      { geslacht: "V", leeftijd: 15, punt: 2, score_min: 8 },
      { geslacht: "V", leeftijd: 15, punt: 3, score_min: 10 },
      { geslacht: "V", leeftijd: 15, punt: 4, score_min: 11 },
      { geslacht: "V", leeftijd: 15, punt: 5, score_min: 12 },
      { geslacht: "V", leeftijd: 15, punt: 6, score_min: 14 },
      { geslacht: "V", leeftijd: 15, punt: 7, score_min: 15 },
      { geslacht: "V", leeftijd: 15, punt: 8, score_min: 16 },
      { geslacht: "V", leeftijd: 15, punt: 9, score_min: 18 },
      { geslacht: "V", leeftijd: 15, punt: 10, score_min: 19 },
      { geslacht: "V", leeftijd: 15, punt: 11, score_min: 20 },
      { geslacht: "V", leeftijd: 15, punt: 12, score_min: 21 },
      { geslacht: "V", leeftijd: 15, punt: 13, score_min: 22 },
      { geslacht: "V", leeftijd: 15, punt: 14, score_min: 23 },
      { geslacht: "V", leeftijd: 15, punt: 15, score_min: 24 },
      { geslacht: "V", leeftijd: 15, punt: 16, score_min: 25 },
      { geslacht: "V", leeftijd: 15, punt: 17, score_min: 26 },
      { geslacht: "V", leeftijd: 15, punt: 18, score_min: 27 },
      { geslacht: "V", leeftijd: 15, punt: 19, score_min: 28 },
      { geslacht: "V", leeftijd: 15, punt: 20, score_min: 29 },
      // 16 jaar
      { geslacht: "V", leeftijd: 16, punt: 1, score_min: 8 },
      { geslacht: "V", leeftijd: 16, punt: 2, score_min: 9 },
      { geslacht: "V", leeftijd: 16, punt: 3, score_min: 11 },
      { geslacht: "V", leeftijd: 16, punt: 4, score_min: 12 },
      { geslacht: "V", leeftijd: 16, punt: 5, score_min: 13 },
      { geslacht: "V", leeftijd: 16, punt: 6, score_min: 15 },
      { geslacht: "V", leeftijd: 16, punt: 7, score_min: 16 },
      { geslacht: "V", leeftijd: 16, punt: 8, score_min: 17 },
      { geslacht: "V", leeftijd: 16, punt: 9, score_min: 19 },
      { geslacht: "V", leeftijd: 16, punt: 10, score_min: 20 },
      { geslacht: "V", leeftijd: 16, punt: 11, score_min: 21 },
      { geslacht: "V", leeftijd: 16, punt: 12, score_min: 22 },
      { geslacht: "V", leeftijd: 16, punt: 13, score_min: 23 },
      { geslacht: "V", leeftijd: 16, punt: 14, score_min: 24 },
      { geslacht: "V", leeftijd: 16, punt: 15, score_min: 25 },
      { geslacht: "V", leeftijd: 16, punt: 16, score_min: 26 },
      { geslacht: "V", leeftijd: 16, punt: 17, score_min: 27 },
      { geslacht: "V", leeftijd: 16, punt: 18, score_min: 28 },
      { geslacht: "V", leeftijd: 16, punt: 19, score_min: 29 },
      { geslacht: "V", leeftijd: 16, punt: 20, score_min: 30 },
      // 17 jaar
      { geslacht: "V", leeftijd: 17, punt: 1, score_min: 8 },
      { geslacht: "V", leeftijd: 17, punt: 2, score_min: 9 },
      { geslacht: "V", leeftijd: 17, punt: 3, score_min: 11 },
      { geslacht: "V", leeftijd: 17, punt: 4, score_min: 12 },
      { geslacht: "V", leeftijd: 17, punt: 5, score_min: 13 },
      { geslacht: "V", leeftijd: 17, punt: 6, score_min: 15 },
      { geslacht: "V", leeftijd: 17, punt: 7, score_min: 16 },
      { geslacht: "V", leeftijd: 17, punt: 8, score_min: 17 },
      { geslacht: "V", leeftijd: 17, punt: 9, score_min: 19 },
      { geslacht: "V", leeftijd: 17, punt: 10, score_min: 20 },
      { geslacht: "V", leeftijd: 17, punt: 11, score_min: 21 },
      { geslacht: "V", leeftijd: 17, punt: 12, score_min: 22 },
      { geslacht: "V", leeftijd: 17, punt: 13, score_min: 23 },
      { geslacht: "V", leeftijd: 17, punt: 14, score_min: 24 },
      { geslacht: "V", leeftijd: 17, punt: 15, score_min: 25 },
      { geslacht: "V", leeftijd: 17, punt: 16, score_min: 26 },
      { geslacht: "V", leeftijd: 17, punt: 17, score_min: 27 },
      { geslacht: "V", leeftijd: 17, punt: 18, score_min: 28 },
      { geslacht: "V", leeftijd: 17, punt: 19, score_min: 29 },
      { geslacht: "V", leeftijd: 17, punt: 20, score_min: 30 }
    ]
  },
  'normen_sit_and_reach': {
    "test_id": "sit_and_reach",
    "school_id": "ka_beveren",
    "score_richting": "hoog",
    "nulpunt_offset": 15,
    "punten_schaal": [
      // Jongens
      // 14 jaar
      { geslacht: "M", leeftijd: 14, punt: 1, score_min: 2 },
      { geslacht: "M", leeftijd: 14, punt: 2, score_min: 3 },
      { geslacht: "M", leeftijd: 14, punt: 3, score_min: 5 },
      { geslacht: "M", leeftijd: 14, punt: 4, score_min: 6 },
      { geslacht: "M", leeftijd: 14, punt: 5, score_min: 8 },
      { geslacht: "M", leeftijd: 14, punt: 6, score_min: 9 },
      { geslacht: "M", leeftijd: 14, punt: 7, score_min: 11 },
      { geslacht: "M", leeftijd: 14, punt: 8, score_min: 12 },
      { geslacht: "M", leeftijd: 14, punt: 9, score_min: 14 },
      { geslacht: "M", leeftijd: 14, punt: 10, score_min: 15 },
      { geslacht: "M", leeftijd: 14, punt: 11, score_min: 17 },
      { geslacht: "M", leeftijd: 14, punt: 12, score_min: 18 },
      { geslacht: "M", leeftijd: 14, punt: 13, score_min: 20 },
      { geslacht: "M", leeftijd: 14, punt: 14, score_min: 22 },
      { geslacht: "M", leeftijd: 14, punt: 15, score_min: 24 },
      { geslacht: "M", leeftijd: 14, punt: 16, score_min: 25 },
      { geslacht: "M", leeftijd: 14, punt: 17, score_min: 27 },
      { geslacht: "M", leeftijd: 14, punt: 18, score_min: 29 },
      { geslacht: "M", leeftijd: 14, punt: 19, score_min: 30 },
      { geslacht: "M", leeftijd: 14, punt: 20, score_min: 32 },
      // 15 jaar
      { geslacht: "M", leeftijd: 15, punt: 1, score_min: 2 },
      { geslacht: "M", leeftijd: 15, punt: 2, score_min: 4 },
      { geslacht: "M", leeftijd: 15, punt: 3, score_min: 5 },
      { geslacht: "M", leeftijd: 15, punt: 4, score_min: 7 },
      { geslacht: "M", leeftijd: 15, punt: 5, score_min: 8 },
      { geslacht: "M", leeftijd: 15, punt: 6, score_min: 10 },
      { geslacht: "M", leeftijd: 15, punt: 7, score_min: 11 },
      { geslacht: "M", leeftijd: 15, punt: 8, score_min: 13 },
      { geslacht: "M", leeftijd: 15, punt: 9, score_min: 14 },
      { geslacht: "M", leeftijd: 15, punt: 10, score_min: 16 },
      { geslacht: "M", leeftijd: 15, punt: 11, score_min: 18 },
      { geslacht: "M", leeftijd: 15, punt: 12, score_min: 19 },
      { geslacht: "M", leeftijd: 15, punt: 13, score_min: 21 },
      { geslacht: "M", leeftijd: 15, punt: 14, score_min: 23 },
      { geslacht: "M", leeftijd: 15, punt: 15, score_min: 25 },
      { geslacht: "M", leeftijd: 15, punt: 16, score_min: 26 },
      { geslacht: "M", leeftijd: 15, punt: 17, score_min: 28 },
      { geslacht: "M", leeftijd: 15, punt: 18, score_min: 30 },
      { geslacht: "M", leeftijd: 15, punt: 19, score_min: 31 },
      { geslacht: "M", leeftijd: 15, punt: 20, score_min: 33 },
      // 16 jaar
      { geslacht: "M", leeftijd: 16, punt: 1, score_min: 3 },
      { geslacht: "M", leeftijd: 16, punt: 2, score_min: 5 },
      { geslacht: "M", leeftijd: 16, punt: 3, score_min: 6 },
      { geslacht: "M", leeftijd: 16, punt: 4, score_min: 8 },
      { geslacht: "M", leeftijd: 16, punt: 5, score_min: 9 },
      { geslacht: "M", leeftijd: 16, punt: 6, score_min: 11 },
      { geslacht: "M", leeftijd: 16, punt: 7, score_min: 12 },
      { geslacht: "M", leeftijd: 16, punt: 8, score_min: 14 },
      { geslacht: "M", leeftijd: 16, punt: 9, score_min: 15 },
      { geslacht: "M", leeftijd: 16, punt: 10, score_min: 17 },
      { geslacht: "M", leeftijd: 16, punt: 11, score_min: 19 },
      { geslacht: "M", leeftijd: 16, punt: 12, score_min: 20 },
      { geslacht: "M", leeftijd: 16, punt: 13, score_min: 22 },
      { geslacht: "M", leeftijd: 16, punt: 14, score_min: 24 },
      { geslacht: "M", leeftijd: 16, punt: 15, score_min: 26 },
      { geslacht: "M", leeftijd: 16, punt: 16, score_min: 27 },
      { geslacht: "M", leeftijd: 16, punt: 17, score_min: 29 },
      { geslacht: "M", leeftijd: 16, punt: 18, score_min: 31 },
      { geslacht: "M", leeftijd: 16, punt: 19, score_min: 32 },
      { geslacht: "M", leeftijd: 16, punt: 20, score_min: 34 },
      // 17 jaar
      { geslacht: "M", leeftijd: 17, punt: 1, score_min: 3 },
      { geslacht: "M", leeftijd: 17, punt: 2, score_min: 5 },
      { geslacht: "M", leeftijd: 17, punt: 3, score_min: 6 },
      { geslacht: "M", leeftijd: 17, punt: 4, score_min: 8 },
      { geslacht: "M", leeftijd: 17, punt: 5, score_min: 10 },
      { geslacht: "M", leeftijd: 17, punt: 6, score_min: 11 },
      { geslacht: "M", leeftijd: 17, punt: 7, score_min: 13 },
      { geslacht: "M", leeftijd: 17, punt: 8, score_min: 15 },
      { geslacht: "M", leeftijd: 17, punt: 9, score_min: 16 },
      { geslacht: "M", leeftijd: 17, punt: 10, score_min: 18 },
      { geslacht: "M", leeftijd: 17, punt: 11, score_min: 20 },
      { geslacht: "M", leeftijd: 17, punt: 12, score_min: 21 },
      { geslacht: "M", leeftijd: 17, punt: 13, score_min: 23 },
      { geslacht: "M", leeftijd: 17, punt: 14, score_min: 25 },
      { geslacht: "M", leeftijd: 17, punt: 15, score_min: 27 },
      { geslacht: "M", leeftijd: 17, punt: 16, score_min: 28 },
      { geslacht: "M", leeftijd: 17, punt: 17, score_min: 30 },
      { geslacht: "M", leeftijd: 17, punt: 18, score_min: 32 },
      { geslacht: "M", leeftijd: 17, punt: 19, score_min: 33 },
      { geslacht: "M", leeftijd: 17, punt: 20, score_min: 35 },
      // Meisjes
      // 14 jaar
      { geslacht: "V", leeftijd: 14, punt: 1, score_min: 5 },
      { geslacht: "V", leeftijd: 14, punt: 2, score_min: 7 },
      { geslacht: "V", leeftijd: 14, punt: 3, score_min: 9 },
      { geslacht: "V", leeftijd: 14, punt: 4, score_min: 10 },
      { geslacht: "V", leeftijd: 14, punt: 5, score_min: 12 },
      { geslacht: "V", leeftijd: 14, punt: 6, score_min: 14 },
      { geslacht: "V", leeftijd: 14, punt: 7, score_min: 16 },
      { geslacht: "V", leeftijd: 14, punt: 8, score_min: 17 },
      { geslacht: "V", leeftijd: 14, punt: 9, score_min: 19 },
      { geslacht: "V", leeftijd: 14, punt: 10, score_min: 21 },
      { geslacht: "V", leeftijd: 14, punt: 11, score_min: 23 },
      { geslacht: "V", leeftijd: 14, punt: 12, score_min: 24 },
      { geslacht: "V", leeftijd: 14, punt: 13, score_min: 26 },
      { geslacht: "V", leeftijd: 14, punt: 14, score_min: 28 },
      { geslacht: "V", leeftijd: 14, punt: 15, score_min: 30 },
      { geslacht: "V", leeftijd: 14, punt: 16, score_min: 31 },
      { geslacht: "V", leeftijd: 14, punt: 17, score_min: 33 },
      { geslacht: "V", leeftijd: 14, punt: 18, score_min: 35 },
      { geslacht: "V", leeftijd: 14, punt: 19, score_min: 36 },
      { geslacht: "V", leeftijd: 14, punt: 20, score_min: 38 },
      // 15 jaar
      { geslacht: "V", leeftijd: 15, punt: 1, score_min: 5 },
      { geslacht: "V", leeftijd: 15, punt: 2, score_min: 7 },
      { geslacht: "V", leeftijd: 15, punt: 3, score_min: 9 },
      { geslacht: "V", leeftijd: 15, punt: 4, score_min: 11 },
      { geslacht: "V", leeftijd: 15, punt: 5, score_min: 13 },
      { geslacht: "V", leeftijd: 15, punt: 6, score_min: 14 },
      { geslacht: "V", leeftijd: 15, punt: 7, score_min: 16 },
      { geslacht: "V", leeftijd: 15, punt: 8, score_min: 18 },
      { geslacht: "V", leeftijd: 15, punt: 9, score_min: 20 },
      { geslacht: "V", leeftijd: 15, punt: 10, score_min: 22 },
      { geslacht: "V", leeftijd: 15, punt: 11, score_min: 24 },
      { geslacht: "V", leeftijd: 15, punt: 12, score_min: 25 },
      { geslacht: "V", leeftijd: 15, punt: 13, score_min: 27 },
      { geslacht: "V", leeftijd: 15, punt: 14, score_min: 29 },
      { geslacht: "V", leeftijd: 15, punt: 15, score_min: 31 },
      { geslacht: "V", leeftijd: 15, punt: 16, score_min: 32 },
      { geslacht: "V", leeftijd: 15, punt: 17, score_min: 34 },
      { geslacht: "V", leeftijd: 15, punt: 18, score_min: 36 },
      { geslacht: "V", leeftijd: 15, punt: 19, score_min: 37 },
      { geslacht: "V", leeftijd: 15, punt: 20, score_min: 39 },
      // 16 jaar
      { geslacht: "V", leeftijd: 16, punt: 1, score_min: 6 },
      { geslacht: "V", leeftijd: 16, punt: 2, score_min: 8 },
      { geslacht: "V", leeftijd: 16, punt: 3, score_min: 10 },
      { geslacht: "V", leeftijd: 16, punt: 4, score_min: 12 },
      { geslacht: "V", leeftijd: 16, punt: 5, score_min: 14 },
      { geslacht: "V", leeftijd: 16, punt: 6, score_min: 15 },
      { geslacht: "V", leeftijd: 16, punt: 7, score_min: 17 },
      { geslacht: "V", leeftijd: 16, punt: 8, score_min: 19 },
      { geslacht: "V", leeftijd: 16, punt: 9, score_min: 21 },
      { geslacht: "V", leeftijd: 16, punt: 10, score_min: 23 },
      { geslacht: "V", leeftijd: 16, punt: 11, score_min: 25 },
      { geslacht: "V", leeftijd: 16, punt: 12, score_min: 26 },
      { geslacht: "V", leeftijd: 16, punt: 13, score_min: 28 },
      { geslacht: "V", leeftijd: 16, punt: 14, score_min: 30 },
      { geslacht: "V", leeftijd: 16, punt: 15, score_min: 32 },
      { geslacht: "V", leeftijd: 16, punt: 16, score_min: 33 },
      { geslacht: "V", leeftijd: 16, punt: 17, score_min: 35 },
      { geslacht: "V", leeftijd: 16, punt: 18, score_min: 37 },
      { geslacht: "V", leeftijd: 16, punt: 19, score_min: 38 },
      { geslacht: "V", leeftijd: 16, punt: 20, score_min: 40 },
      // 17 jaar
      { geslacht: "V", leeftijd: 17, punt: 1, score_min: 6 },
      { geslacht: "V", leeftijd: 17, punt: 2, score_min: 8 },
      { geslacht: "V", leeftijd: 17, punt: 3, score_min: 10 },
      { geslacht: "V", leeftijd: 17, punt: 4, score_min: 12 },
      { geslacht: "V", leeftijd: 17, punt: 5, score_min: 14 },
      { geslacht: "V", leeftijd: 17, punt: 6, score_min: 16 },
      { geslacht: "V", leeftijd: 17, punt: 7, score_min: 18 },
      { geslacht: "V", leeftijd: 17, punt: 8, score_min: 20 },
      { geslacht: "V", leeftijd: 17, punt: 9, score_min: 22 },
      { geslacht: "V", leeftijd: 17, punt: 10, score_min: 24 },
      { geslacht: "V", leeftijd: 17, punt: 11, score_min: 26 },
      { geslacht: "V", leeftijd: 17, punt: 12, score_min: 27 },
      { geslacht: "V", leeftijd: 17, punt: 13, score_min: 29 },
      { geslacht: "V", leeftijd: 17, punt: 14, score_min: 31 },
      { geslacht: "V", leeftijd: 17, punt: 15, score_min: 33 },
      { geslacht: "V", leeftijd: 17, punt: 16, score_min: 34 },
      { geslacht: "V", leeftijd: 17, punt: 17, score_min: 36 },
      { geslacht: "V", leeftijd: 17, punt: 18, score_min: 38 },
      { geslacht: "V", leeftijd: 17, punt: 19, score_min: 39 },
      { geslacht: "V", leeftijd: 17, punt: 20, score_min: 41 }
    ]
  },
  'normen_triceps_dips': {
    "test_id": "triceps_dips",
    "school_id": "ka_beveren",
    "score_richting": "hoog",
    "protocol": "max_reps",
    "varianten": {
      "M": { "naam": "Triceps dips", "beschrijving": "Dips op bank/barre, benen gestrekt." },
      "V": { "naam": "Triceps dips (geknikte benen)", "beschrijving": "Dips met voeten op de grond en geknikte benen, zelfde puntenschaal." }
    },
    "punten_schaal": [
      // Jongens
      // 14 jaar
      { geslacht: "M", leeftijd: 14, punt: 1, score_min: 1 },
      { geslacht: "M", leeftijd: 14, punt: 2, score_min: 2 },
      { geslacht: "M", leeftijd: 14, punt: 3, score_min: 3 },
      { geslacht: "M", leeftijd: 14, punt: 4, score_min: 4 },
      { geslacht: "M", leeftijd: 14, punt: 5, score_min: 5 },
      { geslacht: "M", leeftijd: 14, punt: 6, score_min: 7 },
      { geslacht: "M", leeftijd: 14, punt: 7, score_min: 8 },
      { geslacht: "M", leeftijd: 14, punt: 8, score_min: 9 },
      { geslacht: "M", leeftijd: 14, punt: 9, score_min: 10 },
      { geslacht: "M", leeftijd: 14, punt: 10, score_min: 11 },
      { geslacht: "M", leeftijd: 14, punt: 11, score_min: 13 },
      { geslacht: "M", leeftijd: 14, punt: 12, score_min: 14 },
      { geslacht: "M", leeftijd: 14, punt: 13, score_min: 16 },
      { geslacht: "M", leeftijd: 14, punt: 14, score_min: 17 },
      { geslacht: "M", leeftijd: 14, punt: 15, score_min: 19 },
      { geslacht: "M", leeftijd: 14, punt: 16, score_min: 20 },
      { geslacht: "M", leeftijd: 14, punt: 17, score_min: 22 },
      { geslacht: "M", leeftijd: 14, punt: 18, score_min: 23 },
      { geslacht: "M", leeftijd: 14, punt: 19, score_min: 25 },
      { geslacht: "M", leeftijd: 14, punt: 20, score_min: 26 },
      // 15 jaar
      { geslacht: "M", leeftijd: 15, punt: 1, score_min: 2 },
      { geslacht: "M", leeftijd: 15, punt: 2, score_min: 3 },
      { geslacht: "M", leeftijd: 15, punt: 3, score_min: 4 },
      { geslacht: "M", leeftijd: 15, punt: 4, score_min: 6 },
      { geslacht: "M", leeftijd: 15, punt: 5, score_min: 7 },
      { geslacht: "M", leeftijd: 15, punt: 6, score_min: 8 },
      { geslacht: "M", leeftijd: 15, punt: 7, score_min: 9 },
      { geslacht: "M", leeftijd: 15, punt: 8, score_min: 11 },
      { geslacht: "M", leeftijd: 15, punt: 9, score_min: 12 },
      { geslacht: "M", leeftijd: 15, punt: 10, score_min: 13 },
      { geslacht: "M", leeftijd: 15, punt: 11, score_min: 15 },
      { geslacht: "M", leeftijd: 15, punt: 12, score_min: 16 },
      { geslacht: "M", leeftijd: 15, punt: 13, score_min: 18 },
      { geslacht: "M", leeftijd: 15, punt: 14, score_min: 19 },
      { geslacht: "M", leeftijd: 15, punt: 15, score_min: 21 },
      { geslacht: "M", leeftijd: 15, punt: 16, score_min: 23 },
      { geslacht: "M", leeftijd: 15, punt: 17, score_min: 24 },
      { geslacht: "M", leeftijd: 15, punt: 18, score_min: 26 },
      { geslacht: "M", leeftijd: 15, punt: 19, score_min: 27 },
      { geslacht: "M", leeftijd: 15, punt: 20, score_min: 29 },
      // 16 jaar
      { geslacht: "M", leeftijd: 16, punt: 1, score_min: 2 },
      { geslacht: "M", leeftijd: 16, punt: 2, score_min: 3 },
      { geslacht: "M", leeftijd: 16, punt: 3, score_min: 5 },
      { geslacht: "M", leeftijd: 16, punt: 4, score_min: 6 },
      { geslacht: "M", leeftijd: 16, punt: 5, score_min: 8 },
      { geslacht: "M", leeftijd: 16, punt: 6, score_min: 9 },
      { geslacht: "M", leeftijd: 16, punt: 7, score_min: 11 },
      { geslacht: "M", leeftijd: 16, punt: 8, score_min: 12 },
      { geslacht: "M", leeftijd: 16, punt: 9, score_min: 14 },
      { geslacht: "M", leeftijd: 16, punt: 10, score_min: 15 },
      { geslacht: "M", leeftijd: 16, punt: 11, score_min: 17 },
      { geslacht: "M", leeftijd: 16, punt: 12, score_min: 18 },
      { geslacht: "M", leeftijd: 16, punt: 13, score_min: 20 },
      { geslacht: "M", leeftijd: 16, punt: 14, score_min: 22 },
      { geslacht: "M", leeftijd: 16, punt: 15, score_min: 24 },
      { geslacht: "M", leeftijd: 16, punt: 16, score_min: 25 },
      { geslacht: "M", leeftijd: 16, punt: 17, score_min: 27 },
      { geslacht: "M", leeftijd: 16, punt: 18, score_min: 29 },
      { geslacht: "M", leeftijd: 16, punt: 19, score_min: 30 },
      { geslacht: "M", leeftijd: 16, punt: 20, score_min: 32 },
      // 17 jaar
      { geslacht: "M", leeftijd: 17, punt: 1, score_min: 3 },
      { geslacht: "M", leeftijd: 17, punt: 2, score_min: 4 },
      { geslacht: "M", leeftijd: 17, punt: 3, score_min: 6 },
      { geslacht: "M", leeftijd: 17, punt: 4, score_min: 7 },
      { geslacht: "M", leeftijd: 17, punt: 5, score_min: 9 },
      { geslacht: "M", leeftijd: 17, punt: 6, score_min: 10 },
      { geslacht: "M", leeftijd: 17, punt: 7, score_min: 12 },
      { geslacht: "M", leeftijd: 17, punt: 8, score_min: 13 },
      { geslacht: "M", leeftijd: 17, punt: 9, score_min: 15 },
      { geslacht: "M", leeftijd: 17, punt: 10, score_min: 16 },
      { geslacht: "M", leeftijd: 17, punt: 11, score_min: 18 },
      { geslacht: "M", leeftijd: 17, punt: 12, score_min: 20 },
      { geslacht: "M", leeftijd: 17, punt: 13, score_min: 22 },
      { geslacht: "M", leeftijd: 17, punt: 14, score_min: 24 },
      { geslacht: "M", leeftijd: 17, punt: 15, score_min: 26 },
      { geslacht: "M", leeftijd: 17, punt: 16, score_min: 27 },
      { geslacht: "M", leeftijd: 17, punt: 17, score_min: 29 },
      { geslacht: "M", leeftijd: 17, punt: 18, score_min: 31 },
      { geslacht: "M", leeftijd: 17, punt: 19, score_min: 33 },
      { geslacht: "M", leeftijd: 17, punt: 20, score_min: 35 },
      // Meisjes
      // 14 jaar
      { geslacht: "V", leeftijd: 14, punt: 1, score_min: 1 },
      { geslacht: "V", leeftijd: 14, punt: 2, score_min: 2 },
      { geslacht: "V", leeftijd: 14, punt: 3, score_min: 3 },
      { geslacht: "V", leeftijd: 14, punt: 4, score_min: 4 },
      { geslacht: "V", leeftijd: 14, punt: 5, score_min: 5 },
      { geslacht: "V", leeftijd: 14, punt: 6, score_min: 7 },
      { geslacht: "V", leeftijd: 14, punt: 7, score_min: 8 },
      { geslacht: "V", leeftijd: 14, punt: 8, score_min: 9 },
      { geslacht: "V", leeftijd: 14, punt: 9, score_min: 10 },
      { geslacht: "V", leeftijd: 14, punt: 10, score_min: 11 },
      { geslacht: "V", leeftijd: 14, punt: 11, score_min: 13 },
      { geslacht: "V", leeftijd: 14, punt: 12, score_min: 14 },
      { geslacht: "V", leeftijd: 14, punt: 13, score_min: 16 },
      { geslacht: "V", leeftijd: 14, punt: 14, score_min: 17 },
      { geslacht: "V", leeftijd: 14, punt: 15, score_min: 19 },
      { geslacht: "V", leeftijd: 14, punt: 16, score_min: 20 },
      { geslacht: "V", leeftijd: 14, punt: 17, score_min: 22 },
      { geslacht: "V", leeftijd: 14, punt: 18, score_min: 23 },
      { geslacht: "V", leeftijd: 14, punt: 19, score_min: 25 },
      { geslacht: "V", leeftijd: 14, punt: 20, score_min: 26 },
      // 15 jaar
      { geslacht: "V", leeftijd: 15, punt: 1, score_min: 2 },
      { geslacht: "V", leeftijd: 15, punt: 2, score_min: 3 },
      { geslacht: "V", leeftijd: 15, punt: 3, score_min: 4 },
      { geslacht: "V", leeftijd: 15, punt: 4, score_min: 6 },
      { geslacht: "V", leeftijd: 15, punt: 5, score_min: 7 },
      { geslacht: "V", leeftijd: 15, punt: 6, score_min: 8 },
      { geslacht: "V", leeftijd: 15, punt: 7, score_min: 9 },
      { geslacht: "V", leeftijd: 15, punt: 8, score_min: 11 },
      { geslacht: "V", leeftijd: 15, punt: 9, score_min: 12 },
      { geslacht: "V", leeftijd: 15, punt: 10, score_min: 13 },
      { geslacht: "V", leeftijd: 15, punt: 11, score_min: 15 },
      { geslacht: "V", leeftijd: 15, punt: 12, score_min: 16 },
      { geslacht: "V", leeftijd: 15, punt: 13, score_min: 18 },
      { geslacht: "V", leeftijd: 15, punt: 14, score_min: 19 },
      { geslacht: "V", leeftijd: 15, punt: 15, score_min: 21 },
      { geslacht: "V", leeftijd: 15, punt: 16, score_min: 23 },
      { geslacht: "V", leeftijd: 15, punt: 17, score_min: 24 },
      { geslacht: "V", leeftijd: 15, punt: 18, score_min: 26 },
      { geslacht: "V", leeftijd: 15, punt: 19, score_min: 27 },
      { geslacht: "V", leeftijd: 15, punt: 20, score_min: 29 },
      // 16 jaar
      { geslacht: "V", leeftijd: 16, punt: 1, score_min: 2 },
      { geslacht: "V", leeftijd: 16, punt: 2, score_min: 3 },
      { geslacht: "V", leeftijd: 16, punt: 3, score_min: 5 },
      { geslacht: "V", leeftijd: 16, punt: 4, score_min: 6 },
      { geslacht: "V", leeftijd: 16, punt: 5, score_min: 8 },
      { geslacht: "V", leeftijd: 16, punt: 6, score_min: 9 },
      { geslacht: "V", leeftijd: 16, punt: 7, score_min: 11 },
      { geslacht: "V", leeftijd: 16, punt: 8, score_min: 12 },
      { geslacht: "V", leeftijd: 16, punt: 9, score_min: 14 },
      { geslacht: "V", leeftijd: 16, punt: 10, score_min: 15 },
      { geslacht: "V", leeftijd: 16, punt: 11, score_min: 17 },
      { geslacht: "V", leeftijd: 16, punt: 12, score_min: 18 },
      { geslacht: "V", leeftijd: 16, punt: 13, score_min: 20 },
      { geslacht: "V", leeftijd: 16, punt: 14, score_min: 22 },
      { geslacht: "V", leeftijd: 16, punt: 15, score_min: 24 },
      { geslacht: "V", leeftijd: 16, punt: 16, score_min: 25 },
      { geslacht: "V", leeftijd: 16, punt: 17, score_min: 27 },
      { geslacht: "V", leeftijd: 16, punt: 18, score_min: 29 },
      { geslacht: "V", leeftijd: 16, punt: 19, score_min: 30 },
      { geslacht: "V", leeftijd: 16, punt: 20, score_min: 32 },
      // 17 jaar
      { geslacht: "V", leeftijd: 17, punt: 1, score_min: 3 },
      { geslacht: "V", leeftijd: 17, punt: 2, score_min: 4 },
      { geslacht: "V", leeftijd: 17, punt: 3, score_min: 6 },
      { geslacht: "V", leeftijd: 17, punt: 4, score_min: 7 },
      { geslacht: "V", leeftijd: 17, punt: 5, score_min: 9 },
      { geslacht: "V", leeftijd: 17, punt: 6, score_min: 10 },
      { geslacht: "V", leeftijd: 17, punt: 7, score_min: 12 },
      { geslacht: "V", leeftijd: 17, punt: 8, score_min: 13 },
      { geslacht: "V", leeftijd: 17, punt: 9, score_min: 15 },
      { geslacht: "V", leeftijd: 17, punt: 10, score_min: 16 },
      { geslacht: "V", leeftijd: 17, punt: 11, score_min: 18 },
      { geslacht: "V", leeftijd: 17, punt: 12, score_min: 20 },
      { geslacht: "V", leeftijd: 17, punt: 13, score_min: 22 },
      { geslacht: "V", leeftijd: 17, punt: 14, score_min: 24 },
      { geslacht: "V", leeftijd: 17, punt: 15, score_min: 26 },
      { geslacht: "V", leeftijd: 17, punt: 16, score_min: 27 },
      { geslacht: "V", leeftijd: 17, punt: 17, score_min: 29 },
      { geslacht: "V", leeftijd: 17, punt: 18, score_min: 31 },
      { geslacht: "V", leeftijd: 17, punt: 19, score_min: 33 },
      { geslacht: "V", leeftijd: 17, punt: 20, score_min: 35 }
    ]
  }
};

async function importAlles() {
  console.log('Start import van 4 nieuwe testen...');
  for (const [id, data] of Object.entries(testen)) {
    await db.collection('testen').doc(id).set(data);
    console.log(`✅ Test '${id}' toegevoegd.`);
  }
  console.log('\nStart import van bijhorende normen...');
  for (const [id, data] of Object.entries(normen)) {
    await db.collection('normen').doc(id).set(data);
    console.log(`✅ Normen '${id}' toegevoegd (${data.punten_schaal.length} rijen).`);
  }
  console.log('\n🎉 Import voltooid!');
}

importAlles();
